apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-4py0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-4py0
    app.kubernetes.io/part-of: my-app-3
  name: java-springboot-hello-4py0
  namespace: mreid-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: java-springboot-hello-4py0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: java-springboot-hello-4py0
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/mreid-tenant/my-app-3/java-springboot-hello-4py0@sha256:ec6cf64925b74660897f9a8c865f1e3a591b8ff3048cb3b680b9349daf3d3d33
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
