apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-4py0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-4py0
    app.kubernetes.io/part-of: my-app-3
  name: java-springboot-hello-4py0
  namespace: mreid-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: java-springboot-hello-4py0
status:
  loadBalancer: {}
